[book]
title = "Delegation Receipt Standard"
authors = ["Okey"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/OkeyAmy/DRS"
edit-url-template = "https://github.com/OkeyAmy/DRS/edit/main/docs-site/{path}"
additional-css = ["theme/css/custom.css"]
no-section-label = false

[output.html.search]
enable = true
limit-results = 20
use-boolean-and = true
