/**
 * Type stub for @drs/wasm — generated by wasm-pack from drs-core.
 * The package is an optional peer dependency: the SDK works without it
 * by falling back to VerifyClient (HTTP). This declaration keeps tsc
 * happy at build time before the WASM package exists.
 */
declare module "@drs/wasm" {
  /** Initialises the WASM binary. Must be awaited before calling any export. */
  const init: (url?: string) => Promise<void>;
  export default init;

  /** Verifies a DRS bundle JSON string. Returns a JSON result string. */
  export function verify_chain(bundleJson: string): string;
}
